ifcs:
  options:
    log_level: "off"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.77700_B"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"

  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KRFEC"
    id: "249"
    lanes: "0:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "249"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "253"
    lanes: "4:4"
    serdes_group: "31"
    speed: "100G"
    sysport: "253"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "245"
    lanes: "4:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "245"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "241"
    lanes: "0:4"
    serdes_group: "30"
    speed: "100G"
    sysport: "241"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "233"
    lanes: "0:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "233"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "237"
    lanes: "4:4"
    serdes_group: "29"
    speed: "100G"
    sysport: "237"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "229"
    lanes: "4:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "229"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "225"
    lanes: "0:4"
    serdes_group: "28"
    speed: "100G"
    sysport: "225"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "217"
    lanes: "0:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "217"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "221"
    lanes: "4:4"
    serdes_group: "27"
    speed: "100G"
    sysport: "221"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "213"
    lanes: "4:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "213"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "209"
    lanes: "0:4"
    serdes_group: "26"
    speed: "100G"
    sysport: "209"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "201"
    lanes: "0:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "201"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "205"
    lanes: "4:4"
    serdes_group: "25"
    speed: "100G"
    sysport: "205"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "197"
    lanes: "4:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "197"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "193"
    lanes: "0:4"
    serdes_group: "24"
    speed: "100G"
    sysport: "193"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "185"
    lanes: "0:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "185"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "189"
    lanes: "4:4"
    serdes_group: "23"
    speed: "100G"
    sysport: "189"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "181"
    lanes: "4:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "181"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "177"
    lanes: "0:4"
    serdes_group: "22"
    speed: "100G"
    sysport: "177"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "169"
    lanes: "0:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "169"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "173"
    lanes: "4:4"
    serdes_group: "21"
    speed: "100G"
    sysport: "173"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "165"
    lanes: "4:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "165"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "161"
    lanes: "0:4"
    serdes_group: "20"
    speed: "100G"
    sysport: "161"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "153"
    lanes: "0:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "153"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "157"
    lanes: "4:4"
    serdes_group: "19"
    speed: "100G"
    sysport: "157"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "149"
    lanes: "4:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "149"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "145"
    lanes: "0:4"
    serdes_group: "18"
    speed: "100G"
    sysport: "145"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "137"
    lanes: "0:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "137"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "141"
    lanes: "4:4"
    serdes_group: "17"
    speed: "100G"
    sysport: "141"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "133"
    lanes: "4:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "133"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "129"
    lanes: "0:4"
    serdes_group: "16"
    speed: "100G"
    sysport: "129"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "121"
    lanes: "0:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "121"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "125"
    lanes: "4:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "125"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "117"
    lanes: "4:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "117"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "113"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "113"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "105"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "105"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "109"
    lanes: "4:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "109"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "101"
    lanes: "4:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "101"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "97"
    lanes: "0:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "97"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "89"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "89"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "93"
    lanes: "4:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "93"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "85"
    lanes: "4:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "85"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "81"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "81"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "73"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "73"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "77"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "77"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "69"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "69"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "65"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "65"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "57"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "61"
    lanes: "4:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "61"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "53"
    lanes: "4:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "53"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "49"
    lanes: "0:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "49"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "53"
    lanes: "0:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "53"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "45"
    lanes: "4:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "45"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "37"
    lanes: "4:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "37"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "33"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "33"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "57"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "57"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "29"
    lanes: "4:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "29"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "21"
    lanes: "4:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "21"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "17"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "61"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "61"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "13"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "13"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "5"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "5"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "KRFEC"
    id: "1"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
    admin_state: "true"
    loopback: "none"
  - fec: "NONE"
    id: "257"
    lanes: "0:1"
    serdes_group: "32"
    speed: "10G"
    sysport: "257"
    type: "mgmt 0"
    admin_state: "true"
    loopback: "none"
  - fec: "NONE"
    id: "258"
    lanes: "1:1"
    serdes_group: "32"
    speed: "10G"
    sysport: "258"
    type: "mgmt 1"
    admin_state: "true"
    loopback: "none"
  isg:
  - id: "0"
    lane_swap: "01234567"
    rx_polarity: "01110001"
    tx_polarity: "00101001"
  - id: "1"
    lane_swap: "01234567"
    rx_polarity: "11100100"
    tx_polarity: "10111111"
  - id: "2"
    lane_swap: "01234567"
    rx_polarity: "00010001"
    tx_polarity: "00100010"
  - id: "3"
    lane_swap: "01234567"
    rx_polarity: "11011101"
    tx_polarity: "00101010"
  - id: "4"
    lane_swap: "01234567"
    rx_polarity: "10010101"
    tx_polarity: "10111110"
  - id: "5"
    lane_swap: "01234567"
    rx_polarity: "10111001"
    tx_polarity: "01101000"
  - id: "6"
    lane_swap: "01234567"
    rx_polarity: "01110011"
    tx_polarity: "01110110"
  - id: "7"
    lane_swap: "01234567"
    rx_polarity: "10111001"
    tx_polarity: "01001000"
  - id: "8"
    lane_swap: "01234567"
    rx_polarity: "01000000"
    tx_polarity: "11000100"
  - id: "9"
    lane_swap: "01234567"
    rx_polarity: "10100100"
    tx_polarity: "10001010"
  - id: "10"
    lane_swap: "01234567"
    rx_polarity: "00011101"
    tx_polarity: "11000110"
  - id: "11"
    lane_swap: "01234567"
    rx_polarity: "00000101"
    tx_polarity: "01000111"
  - id: "12"
    lane_swap: "01234567"
    rx_polarity: "11100000"
    tx_polarity: "01111000"
  - id: "13"
    lane_swap: "01234567"
    rx_polarity: "00101111"
    tx_polarity: "10011111"
  - id: "14"
    lane_swap: "01234567"
    rx_polarity: "00011000"
    tx_polarity: "00101001"
  - id: "15"
    lane_swap: "01234567"
    rx_polarity: "00110110"
    tx_polarity: "10110111"
  - id: "16"
    lane_swap: "01234567"
    rx_polarity: "00000111"
    tx_polarity: "00101001"
  - id: "17"
    lane_swap: "01234567"
    rx_polarity: "10001000"
    tx_polarity: "10100111"
  - id: "18"
    lane_swap: "01234567"
    rx_polarity: "11111110"
    tx_polarity: "00011001"
  - id: "19"
    lane_swap: "01234567"
    rx_polarity: "10011010"
    tx_polarity: "10010101"
  - id: "20"
    lane_swap: "01234567"
    rx_polarity: "01100000"
    tx_polarity: "00101001"
  - id: "21"
    lane_swap: "01234567"
    rx_polarity: "01111001"
    tx_polarity: "10010111"
  - id: "22"
    lane_swap: "01234567"
    rx_polarity: "11010011"
    tx_polarity: "00101001"
  - id: "23"
    lane_swap: "01234567"
    rx_polarity: "01111011"
    tx_polarity: "10110111"
  - id: "24"
    lane_swap: "01234567"
    rx_polarity: "11101011"
    tx_polarity: "00101001"
  - id: "25"
    lane_swap: "01234567"
    rx_polarity: "11010111"
    tx_polarity: "10110111"
  - id: "26"
    lane_swap: "01234567"
    rx_polarity: "00101101"
    tx_polarity: "00100001"
  - id: "27"
    lane_swap: "01234567"
    rx_polarity: "11011001"
    tx_polarity: "11000111"
  - id: "28"
    lane_swap: "01234567"
    rx_polarity: "01010011"
    tx_polarity: "00100001"
  - id: "29"
    lane_swap: "01234567"
    rx_polarity: "01111001"
    tx_polarity: "10110111"
  - id: "30"
    lane_swap: "01234567"
    rx_polarity: "00110001"
    tx_polarity: "00101001"
  - id: "31"
    lane_swap: "01234567"
    rx_polarity: "01101101"
    tx_polarity: "10110101"
  - id: "32"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00000000"
